//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCareSupport02.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BloodDonare
    {
        public int Id { get; set; }


        [Required]
        [StringLength(20, MinimumLength = 2)]
        [Display(Name = "Donor Name")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Gender")]
        public int GenderId { get; set; }

        [Required]
        [Display(Name = "Blood Group")]
        public int BloodGroupId { get; set; }

        [Required]
        [Display(Name = "City")]
        public int CityId { get; set; }


        [Required]
        [Display(Name = "Sub City")]
        public int SubCityId { get; set; }

        [Required]
        [StringLength(15, MinimumLength = 11)]
        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }
    
        public virtual BloodGroup BloodGroup { get; set; }
        public virtual City City { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual SubCity SubCity { get; set; }
    }
}
