//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCareSupport02.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    //[MetadataType(typeof(Doctor))]
    //public partial class Doctors
    //{
    //    public string ConfirmPassWord { get; set; }
    //}

    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Apointments = new HashSet<Apointment>();
            this.ApointmentFixeds = new HashSet<ApointmentFixed>();
            this.Messeges = new HashSet<Messege>();
            this.Solutions = new HashSet<Solution>();
        }


        public int Id { get; set; }

        [Required]
        [Display(Name = "Doctor Name")]
        [StringLength(30, MinimumLength = 2)]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Date Of Birth")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> DateOfBirth { get; set; }

        [Required]
        [Display(Name = "Gender")]
        public int GenderId { get; set; }


        [Required]
        [Display(Name = "Blood Group")]
        public int BloodGroupId { get; set; }

        [Required]
        [StringLength(11, MinimumLength = 9)]
        public string BMDC_NO { get; set; }


        [Required]
        [Display(Name = "Specialization")]
        
        public int SpecializationId { get; set; }

        [Required]
        [Display(Name = "City")]
        public int CityId { get; set; }

        [Required]
        [Display(Name = "Sub City")]
        public int SubCityId { get; set; }

        [Required]
        [Display(Name = "National Id No.")]
        [StringLength(20, MinimumLength = 12)]
        public string NId { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        [StringLength(15, MinimumLength = 11)]
        public string Phone { get; set; }

        [Required]
        [StringLength(20, MinimumLength = 2)]
        public string Skype { get; set; }

        
        [StringLength(20)]
        public string Hospital { get; set; }


        [Display(Name ="Chember Address")]
        [StringLength(35)]
        public string ChemberAddress { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }


        [Required]
        [StringLength(20, MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string PassWord { get; set; }

        //[DataType(DataType.Password)]
        //[Display(Name = "Confirm Password")]
        //[Compare("PassWord", ErrorMessage ="Password Do Not Match")]
        //public string ConfirmPassWord { get; set; }

        [Display(Name = "Photo")]
        public string DoctorPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apointment> Apointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApointmentFixed> ApointmentFixeds { get; set; }
        public virtual BloodGroup BloodGroup { get; set; }
        public virtual City City { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Specialization Specialization { get; set; }
        public virtual SubCity SubCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Messege> Messeges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solution> Solutions { get; set; }
    }
}
